### ISSUE TITLE
Move Setpoints to Top-Right

### ISSUE THREAD

**Issue by Sumith-UnitDes** [UnitDes-Software/Oxygen8UX#5]
Move the Setpoint to Top-Right corner. Use the defaults values.
![image](https://user-images.githubusercontent.com/109672029/203857745-cd0675e4-4828-4edd-9cf0-7d7866108cdc.png)

Like this.
![image](https://user-images.githubusercontent.com/109672029/203857780-d8914864-df8e-48a9-a726-59e56e413d94.png)

Don't use this Setpoint (divSetpoint) instead use divSetpoint_1
![image](https://user-images.githubusercontent.com/109672029/203858034-86c2747d-a07f-4e3f-a5a1-0e9fa4e07c70.png)

**Comment by v08nike** [comment]
I solve this issue and push my branch. Please check it.

**Comment by Sumith-UnitDes** [comment]
Good list of sepoints
![image](https://user-images.githubusercontent.com/109672029/205174414-d10880db-9347-418a-bd9b-9446b250958c.png)

Need to remove/delete all these
![image](https://user-images.githubusercontent.com/109672029/205174528-9ee699f3-2557-4fe7-a226-4f0bf97466ec.png)
